#ifndef PRINTOUT_H_INCLUDED
#define PRINTOUT_H_INCLUDED

#include <string>
#include <vector>
#include <unistd.h>

#include "misc.h"
#include "nodeinfo.h"

#define SPEEDTEST_ERROR_NONE 0
#define SPEEDTEST_ERROR_UNDEFINED 100
#define SPEEDTEST_ERROR_WSAERR 99
#define SPEEDTEST_ERROR_SOCKETERR 98
#define SPEEDTEST_ERROR_NORECOGLINK 97
#define SPEEDTEST_ERROR_NOCONNECTION 96
#define SPEEDTEST_ERROR_INVALIDSUB 95
#define SPEEDTEST_ERROR_NONODES 94
#define SPEEDTEST_ERROR_NORESOLVE 93
#define SPEEDTEST_ERROR_RETEST 92
#define SPEEDTEST_ERROR_NOSPEED 91
#define SPEEDTEST_ERROR_UNRECOGFILE 90
#define SPEEDTEST_ERROR_SUBFETCHERR 89
#define SPEEDTEST_ERROR_GEOIPERR 88

#define SPEEDTEST_MESSAGE_WELCOME 0
#define SPEEDTEST_MESSAGE_FOUNDVMESS 1
#define SPEEDTEST_MESSAGE_FOUNDSS 2
#define SPEEDTEST_MESSAGE_FOUNDSSR 3
#define SPEEDTEST_MESSAGE_FOUNDSUB 4
#define SPEEDTEST_MESSAGE_GOTSERVER 5
#define SPEEDTEST_MESSAGE_STARTPING 6
#define SPEEDTEST_MESSAGE_GOTPING 7
#define SPEEDTEST_MESSAGE_STARTSPEED 8
#define SPEEDTEST_MESSAGE_GOTSPEED 9
#define SPEEDTEST_MESSAGE_GOTRESULT 10
#define SPEEDTEST_MESSAGE_TRAFFIC 11
#define SPEEDTEST_MESSAGE_PICSAVING 12
#define SPEEDTEST_MESSAGE_PICSAVED 13
#define SPEEDTEST_MESSAGE_GROUP 14
#define SPEEDTEST_MESSAGE_FETCHSUB 15
#define SPEEDTEST_MESSAGE_BEGIN 16
#define SPEEDTEST_MESSAGE_FOUNDLOCAL 17
#define SPEEDTEST_MESSAGE_PARSING 18
#define SPEEDTEST_MESSAGE_FOUNDUPD 19
#define SPEEDTEST_MESSAGE_PICDATA 20
#define SPEEDTEST_MESSAGE_STARTGPING 21
#define SPEEDTEST_MESSAGE_GOTGPING 22
#define SPEEDTEST_MESSAGE_FOUNDSOCKS 23
#define SPEEDTEST_MESSAGE_STARTGEOIP 24
#define SPEEDTEST_MESSAGE_GOTGEOIP 25
#define SPEEDTEST_MESSAGE_FOUNDSSCONF 26
#define SPEEDTEST_MESSAGE_MULTILINK 27
#define SPEEDTEST_MESSAGE_PICSAVINGMULTI 28
#define SPEEDTEST_MESSAGE_PICSAVEDMULTI 29
#define SPEEDTEST_MESSAGE_STARTUPD 30
#define SPEEDTEST_MESSAGE_GOTUPD 31
#define SPEEDTEST_MESSAGE_FOUNDSSTAP 32
#define SPEEDTEST_MESSAGE_FOUNDNETCH 33
#define SPEEDTEST_MESSAGE_EOF 49

#define SS_DEFAULT_GROUP "SSProvider"
#define SSR_DEFAULT_GROUP "SSRProvider"
#define V2RAY_DEFAULT_GROUP "V2RayProvider"
#define SOCKS_DEFAULT_GROUP "SocksProvider"

void printMsg(int index, nodeInfo *node, bool rpcmode);
void printMsgWithDict(int index, bool rpcmode, std::vector<std::string> dict, std::vector<std::string> trans);
void printMsgDirect(int index, bool rpcmode);

#endif // PRINTOUT_H_INCLUDED
