package("yaml-cpp-static")
    add_deps("cmake")
    add_versions("0.9.0-SNAPSHOT", "3a1c96f2180814a13587144b7f162f1e38ddda7d")
    set_urls("https://github.com/jbeder/yaml-cpp.git")
    on_install(function (package)
                local configs = {}
                table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
                table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
                import("package.tools.cmake").install(package, configs)
            end)
package_end()
